### ISSUE TITLE
AVR4L will not start on Linux Mint 19

### ISSUE THREAD

**Issue by benreu** [abdalmoniem/AVR4L#9]
When trying to launch AVR4L I get this message:

WARNING:  RXTX Version mismatch
	Jar version = RXTX-2.2-20081207 Cloudhopper Build rxtx.cloudhopper.net
	native lib Version = RXTX-2.2pre2
Oct 13, 2018 10:41:20 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/house/.java/.userPrefs/prefs.xml
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.desktop/javax.swing.text.AbstractDocument$DefaultDocumentEventUndoableWrapper cannot be cast to java.desktop/javax.swing.text.AbstractDocument$DefaultDocumentEvent
	at jsyntaxpane.CompoundUndoManager.undoableEditHappened(CompoundUndoManager.java:61)
	at java.desktop/javax.swing.text.AbstractDocument.fireUndoableEditUpdate(AbstractDocument.java:293)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:761)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
	at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
	at java.desktop/javax.swing.text.DefaultEditorKit.read(DefaultEditorKit.java:274)
	at jsyntaxpane.DefaultSyntaxKit.read(DefaultSyntaxKit.java:223)
	at java.desktop/javax.swing.JEditorPane.setText(JEditorPane.java:1428)
	at mainPckg.Main_Frame.<init>(Main_Frame.java:1445)
	at mainPckg.Main_Frame$58.run(Main_Frame.java:3852)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
RXTX fhs_lock() Error: creating lock file: /var/lock/LCK..ttyS18: File exists
RXTX fhs_lock() Error: creating lock file: /var/lock/LCK..ttyS17: File exists
RXTX fhs_lock() Error: creating lock file: /var/lock/LCK..ttyS31: File exists
RXTX fhs_lock() Error: creating lock file: /var/lock/LCK..ttyS7: File exists

**Comment by abdalmoniem** [comment]
it looks like that the RxTx library is not correctly installed or the version you installed doesn't match the required version (RXTX-2.2-20081207 Cloudhopper Build rxtx.cloudhopper.net); it is not mentioned in the readme, I'll update it. For now you can try installing it from [here](http://rxtx.qbang.org/wiki/index.php/Download)
